
version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports: 
      - "3005:3005"
    volumes:
      - /app/node_modules
      - .:/app
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    command: ["npm", "run", "test"]
# version: '3'
# services:
#   mysql:
#     image: mysql:5.7.23
#     container_name: mysql-db
#   volumes:
#     - mysql-volume:/var/lib/mysql
#   environment:
#     MYSQL_ROOT_PASSWORD: 1
#     MYSQL_DATABASE: neighborhood
#     MYSQL_USER: root
#     MYSQL_PASSWORD: 1
#   server:
#     build:
#       dockerfile: Dockerfile.dev
#       context: ./server
#     volumes:
#         - /app/node_modules
#         - ./server:/app
#   client:
#     build:
#       dockerfile: Dockerfile.dev
#       context: ./client
#     volumes:
#       - /app/node_modules
#       - ./client:/app








# version: '3'
# services:
#   postgres:
#     image: 'postgres:latest'
#   redis:
#     image: 'redis:latest'
#   nginx:
#     restart: always
#     build:
#       dockerfile: Dockerfile.dev
#       context: ./nginx
#     ports:
#       - '3050:80'
#   api:
#     build:
#       dockerfile: Dockerfile.dev
#       context: ./server
#     volumes:
#       - /app/node_modules
#       - ./server:/app
#     environment:
#       - REDIS_HOST=redis
#       - REDIS_PORT=6379
#       - PGUSER=postgres
#       - PGHOST=postgres
#       - PGDATABASE=postgres
#       - PGPASSWORD=postgres_password
#       - PGPORT=5432


#   # web:
#   #   build:
#   #     context: .
#   #     dockerfile: Dockerfile.dev
#   #   ports: 
#   #     - "3003:3003"
#   #   volumes:
#   #     - /app/node_modules
#   #     - .:/app
#   # tests:
#   #   build:
#   #     context: .
#   #     dockerfile: Dockerfile.dev
#   #   volumes:
#   #     - /app/node_modules
#   #     - .:/app
#   #   command: ["npm", "run", "test"]