version: "3"
services:
  mysql:
    image: "mysql:5.7.23"
    container_name: "mysql-db"
    ports:
      - "3306"
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - "3050:80"
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      MYSQL_ROOT_PASSWORD: 1
      MYSQL_DATABASE: "neighborhood"
      MYSQL_USER: "root"
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
